config/routes.rb
Rails.application.routes.draw do

  resources :followers
  resources :blog_images
  get 'charges/new'
  get 'charges/create'
  resources :subscriptions do
    collection do
      get :cancel
      get :change
      get :confirm_plan_change
      get :admin
      get :change_hidden
    end
  end
  root 'static_pages#home'
  get '/signup', to: 'clubs#new'
  post '/signup', to: 'clubs#create'
  get '/metrics', to: 'clubs#metrics'
  get  '/help',    to: 'static_pages#help'
  get '/admin', to: 'static_pages#admin'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/getting_started', to: 'static_pages#getting_started'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :clubs do
    collection do
      get :payment_plans
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :students do
    collection do
      get 'attendance'
      get 'schedule_classes'
      get 'student_attendance'
      get 'prospects'
      get 'deactivated'
      get 'absents'
    end
    patch :buy_classes, on: :member
  end
  resources :activities do
    collection do
      get 'scheduled_classes'
      get 'students'
    end
    member do
      get :grading
            put :update_grading
    end
  end
  resources :payment_plans do
    collection do
      get 'students'
    end
  end
  resources :timeslots
  resources :ranks
  resources :payment_plans
  resource :demo, only: :show, controller: :demo
  resources :charges, only: [:new, :create, :delete]
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  resources :blog_posts do
    collection do
      get 'admin'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
      @student = current_club.students.build
  	  @total_prospects = current_club.students.includes(:payment_plan).where(payment_plans: {name: 'Prospect'})
      @prospects = TypeOfStudent.active_prospects(current_club)
      @absent_alert = current_club.absent_alert
      @absent_alert_activation_date = Date.today - current_club.absent_alert
      @students = TypeOfStudent.active_enrolled(current_club)
    end
  end

  def help
  end

  def about
  end

  def getting_started
  end

  def contact
  end

  def admin
    unless admin?
      redirect_to root_url
    end
  end

    private

    def admin?
      if current_club
        if current_club.admin?
          true
        end
      end
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_logged_in.html.erb
<div class="container">
	<section class="club_info">

				<%= render 'shared/club_info' %>

	</section>
</div>

app/views/static_pages/_logged_out.html.erb
<!-- aos css for css anime -->
<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
<!-- scrollreveal js -->
<script src="https://unpkg.com/scrollreveal"></script>
<!--animate css-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
<!--gsap js-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.0.5/gsap.min.js" crossorigin="anonymous"></script>

<section class="section-1  heading">
  <!-- <div class="container-fulid "> -->
  <div class="container vh-70 d-flex align-items-center" >
    <div class="row  pb-5  " >
      <div class=" col col-12 col-md-6  mt-3 mt-md-0 mb-3 mb-md-0  align-self-center banner-text">
        <div class="font-50">Don't let administration<br>
          <span class="red-font font-50">keep you off the mats</span></div>
        <p>Simple attendance recording so you can focus on training</p>
      </div>
      <div class=" col col-12 col-md-6 " data-aos="fade-down" data-aos-easing="linear" data-aos-duration="800">
        <!-- <img class="img-fluid  img-1" src="assets/img/attendrr-img.jpg" alt="" > -->
        <img class="img-fluid img-1" src=<%=image_url('attendrr-master.png') %>  alt="" >
      </div>
    </div>
  </div>
  <!-- </div> -->

  <section>
  <div class="container-fulid ">
    <div class="container">
      <div class="row text-center d-flex justify-content-center">
        <div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/DoUfQg-rcFM" allowfullscreen></iframe>
</div>
      </div>
    </div>
  </div>
</section>

</section>
<section class="section-2">
  <div class="container-fulid ">
    <div class="container vh-70 d-flex align-items-center" >
      <div class="row mt-5 pt-5 pt-md-0 ">
        <div class="col-12 col-md-6 mb-3 mb-md-0 " data-aos="fade-left" data-aos-easing="linear" data-aos-duration="800">
          <img class="img-fluid img-1" src=<%=image_url('any_device_anywhere.png') %>  alt="" >
        </div>
        <div class="col-12 col-md-6 mt-3 mt-md-0  align-self-center section-2-text">
          <div class="font-50">Any device<br>
            <span class="red-font font-50">Any where</span></div>
          <p>Optimized for desktop and mobile, no matter what the size</p>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-3">
  <div class="container-fulid ">
    <div class="container vh-70 d-flex align-items-center mt-4 mt-md-0" >
      <div class="row mt-3 mt-sm-5 pt-3 pt-sm-5 pb-2 pd-sm-5">
        <div class="col-12 col-md-6 mt-3 mt-md-0  mb-3 mb-md-0  align-self-center section-3-text">
          <div class="font-50">Watch your<br>
            <span class="red-font font-50">club grow</span></div>
          <p>Automatic metric tracking ensures your club reaches its full potential, with simple but useful statistics</p>
        </div>
        <div class="col-12 col-md-6" data-aos="fade-left" data-aos-easing="linear" data-aos-duration="800">
          <img class="img-fluid img-1" src=<%=image_url('metrics_lp.png') %>  alt="" >
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-2">
  <div class="container-fulid ">
    <div class="container vh-70 d-flex align-items-center" >
      <div class="row mt-5 pt-5 pt-md-0 ">
        <div class="col-12 col-md-6 mb-3 mb-md-0 " data-aos="fade-left" data-aos-easing="linear" data-aos-duration="800">
          <img class="img-fluid img-1" src=<%=image_url('grading-lp.png') %>  alt="" >
        </div>
        <div class="col-12 col-md-6 mt-3 mt-md-0  align-self-center section-2-text">
          <div class="font-50">Gradings made<br>
            <span class="red-font font-50">easy</span></div>
          <p>Grade students all at once or one-by-one with a single touch</p>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-3">
  <div class="container-fulid ">
    <div class="container vh-70 d-flex align-items-center mt-4 mt-md-0" >
      <div class="row mt-3 mt-sm-5 pt-3 pt-sm-5 pb-2 pd-sm-5">
        <div class="col-12 col-md-6 mt-3 mt-md-0  mb-3 mb-md-0  align-self-center section-3-text">
          <div class="font-50">One touch<br>
            <span class="red-font font-50">attendance recording</span></div>
          <p>Student log in made simple, so you can focus on instructing</p>
        </div>
        <div class="col-12 col-md-6" data-aos="fade-left" data-aos-easing="linear" data-aos-duration="800">
          <img class="img-fluid img-1" src=<%=image_url('attendance_lp.png') %>  alt="" >
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section-4">
  <div class="container-fulid ">
    <div class="container">
      <div class="row text-center d-flex justify-content-center">
        <div class="section-4-text">
          <h1 class="font-50">Join Attendrr for free today!</h1>
          <p>No credit card, no trial period, no commitment required!</p>
          <%= link_to  signup_path,class:"try_btn" do %>
            <button class="clrbox">Start now!</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<button class="animated fadeInDown " onclick="topFunction()" id="scrollTop" title="Go to top"> <i class="up"></i> </button>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>The Attendrr attendance webapp is currently in development to help you rocket-boost your club to new heights.</p>

app/views/static_pages/admin.html.erb
<section class="Admin">
	<% provide(:title, "Admin") %>
	<div class="container mt-5">
		<div class="row">
			<div class="col-12 d-flex justify-content-start  mt-2 mb-2">
				<h1 style="margin-bottom:0px;">Admin</h1>
			</div>
		</div>
		<%= link_to "Clubs", clubs_path %><br>
		<%= link_to "Edit subscriptions", admin_subscriptions_path %><br>
		<%= link_to "Add subscription", new_subscription_path %><br>
		<%= link_to "New blog post", new_blog_post_path %><br>
		<%= link_to "Edit blog posts", admin_blog_posts_path %><br>
		<%= link_to "Blog images", blog_images_path %><br>
		<%= link_to "Followers", followers_path %>
	</div>

</section>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>



<%= stylesheet_link_tag 'clubs', media: 'all' %>

<div class="show-container rounded"> 
	<div class="show-child-container">
  		<header class="show-header">
		    <h1 class="show-title">Contact</h1><br>
		</header>
<p>The Attendrr team is constantly looking for ways to improve and features to add, so if you have any comments or questions, feel free to email <%= mail_to("rhys@attendrr.com", "rhys@attendrr.com") %> </p> 

<p>Or join our <%= link_to "facebook community", "https://www.facebook.com/attendrr/?view_public_for=101194941347353" %></p>
		

  	</div>
</div>

app/views/static_pages/getting_started.html.erb
<%= stylesheet_link_tag 'clubs', media: 'all' %>

<div class="show-container rounded"> 
	<div class="show-child-container">
  		<header class="show-header">
		    <h1 class="show-title">Getting Started</h1><br>
		</header>
			<iframe width="560" height="315" src="https://www.youtube.com/embed/yKTx99kRlks" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  	</div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>Contact us or view the FAQ for help topics</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
	<%= render 'static_pages/logged_in' %>
<% else %>
	<%= render 'logged_out' %>
<% end %>