config/routes.rb
Rails.application.routes.draw do

  resources :followers
  resources :blog_images
  get 'charges/new'
  get 'charges/create'
  resources :subscriptions do
    collection do
      get :cancel
      get :change
      get :confirm_plan_change
      get :admin
      get :change_hidden
    end
  end
  root 'static_pages#home'
  get '/signup', to: 'clubs#new'
  post '/signup', to: 'clubs#create'
  get '/metrics', to: 'clubs#metrics'
  get  '/help',    to: 'static_pages#help'
  get '/admin', to: 'static_pages#admin'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/getting_started', to: 'static_pages#getting_started'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :clubs do
    collection do
      get :payment_plans
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :students do
    collection do
      get 'attendance'
      get 'schedule_classes'
      get 'student_attendance'
      get 'prospects'
      get 'deactivated'
      get 'absents'
    end
    patch :buy_classes, on: :member
  end
  resources :activities do
    collection do
      get 'scheduled_classes'
      get 'students'
    end
    member do
      get :grading
            put :update_grading
    end
  end
  resources :payment_plans do
    collection do
      get 'students'
    end
  end
  resources :timeslots
  resources :ranks
  resources :payment_plans
  resource :demo, only: :show, controller: :demo
  resources :charges, only: [:new, :create, :delete]
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  resources :blog_posts do
    collection do
      get 'admin'
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :club
  has_many :timeslots, dependent: :destroy
  accepts_nested_attributes_for :timeslots,:allow_destroy => true
  has_many :ranks, dependent: :destroy
  has_many :attendances, dependent: :destroy
  accepts_nested_attributes_for :ranks
  validates :club_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  has_many :students, through: :ranks
end

app/models/student.rb
class Student < ApplicationRecord
  include ActiveModel::Dirty
  define_attribute_methods
  belongs_to :club
  belongs_to :payment_plan, optional: true
  default_scope -> { order(:last_name) }
  mount_uploader :picture, PictureUploader
  validates :club_id, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validate :picture_size
  before_save { email.downcase! }
  before_save { state.upcase! }
  #before_create :assign_prospect
  has_many :student_ranks, dependent: :destroy
  has_many :ranks, through: :student_ranks
  has_many :activities, through: :ranks
  accepts_nested_attributes_for :student_ranks
  has_many :attendances, dependent: :destroy
  before_save :handle_payment_plan_changes!

  scope :student_for_attendance, -> (rank_ids) { includes(:ranks).where(:ranks => {id: rank_ids}).distinct }
  scope :last_month,  -> (timeslot_id,date_find) { joins(sanitize_sql_array(['left outer join attendances on attendances.student_id = students.id'])).where('attendances.id is null OR (attendances.timeslot_id != ? AND attendances.attended_on != ?)',timeslot_id,date_find)}

  before_update :check_lost_students

  #can be used in queries in future by full name
  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def buy_classes!
    self.classes_remaining = self.classes_remaining.to_i + self.payment_plan.classes_amount
    save
    create_revenue_record
  end

  def last_attendance
    if self.attendances.any?
      self.attendances.order("created_at").last.attended_on.to_date
    else
      self.club.created_at.to_date
    end
  end


  def unique_activities
   student_activities.map(&:name).uniq
  end

  #def all_acitivities # SPELLING ERROR
   # activitys
  #end

  def club_ranks
    club_activities.map{ |a| a.ranks}.flatten
  end

  def all_ranks
    self.club.activities.map { |a| a.ranks}.flatten
  end

  def first_ranks_of_activities
    club_activities.map { |a| a.ranks.select{ |r| r.position == 0  }}.flatten
  end

  #def current_ranks
    # all ranks where active == true
  #end

  def check_lost_students
    deactivate_status = self.active_changed? && self.active == false
    if deactivate_status
      DailyMetric.create(
        club_id: self.club.id,
        lost_students: 1
      )
    end
  end

  private

    def club_activities
      self.club.activities
    end
 
    def student_activities
     self.ranks.map(&:activity)
    end

    def assign_prospect
      self.payment_plan = self.club.payment_plans.first
    end

    def handle_payment_plan_changes!
      return if created_at.nil?
      changes = self.changes
      if self.classes_remaining_changed?
        original_classes_amount = changes["classes_remaining"][0]
        updated_classes_amount = changes["classes_remaining"][1]
        if original_classes_amount.nil?
          self.classes_remaining = updated_classes_amount
        elsif updated_classes_amount.nil?
          self.classes_remaining = nil
        else
          self.classes_remaining = updated_classes_amount
          create_revenue_record
        end   
      end 
      if self.payment_plan_id_changed? && self.payment_plan.classes_amount.nil?
        self.classes_remaining = nil
      end
    end

    def create_revenue_record
      DailyMetric.create(
          club_id: self.club.id,
          revenue: self.payment_plan.price.to_f
        )
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	require 'students_datable'
	before_action :logged_in_user, only: [:create, :destroy, :new, :edit, :update]
	before_action :correct_club, only: [:index, :show, :destroy,:prospectplan] # Currently does nothing??
	before_action :exceed_student_limit, only: [:create, :new, :student_attendance]

	def index
		if @club = current_club
			@students = TypeOfStudent.active_enrolled(current_club)
			#Average length of membership
			@accumulated_memberships_in_days = 0
			@students.each do |s|
				if s.active?
					n = (Date.today - s.created_at.to_date).to_i
					@accumulated_memberships_in_days += n
				else
					n = (s.updated_at.to_date - s.created_at.to_date).to_i
				end
			end
			if @accumulated_memberships_in_days && @students.count != 0
				@average_membership_length = @accumulated_memberships_in_days / @students.count
			else
				@average_membership_length = 0
			end
			# @items = Item.paginate :page => params[:page], :per_page => 5
		else
			redirect_to root_url
		end
	end

	# Add more classes to students on class package payment plans
	def buy_classes
		@student = Student.find(params[:id])
		@student.buy_classes!
		redirect_to student_path(@student)
	end

	def deactivated
		if @club = current_club
			@students = TypeOfStudent.deactivated_enrolled(current_club)
		else
			redirect_to root_url
		end
	end

	def show
		@student = current_club.students.find_by(id: params[:id])
		@student_activities = @student.unique_activities
		@first_ranks_of_activities = @student.first_ranks_of_activities
		redirect_to root_url if @student.nil?
		if @student.student_since.nil?
			@student_since = @student.created_at.in_time_zone(current_club.time_zone).strftime("%d/%m/%Y")
			@time_ago = @student.created_at
		else
			@student_since = @student.student_since.in_time_zone(current_club.time_zone).strftime("%d/%m/%Y")
			@time_ago = @student_since
		end
	end

	def new
		@payment_plans = current_club.payment_plans.where(active: true)
		@prospect = current_club.payment_plans.first
		@student = Student.new
		@student_ranks = @student.student_ranks.build
		# Gets an array of every rank in the club to pass to @active_ranks
		@ranks = current_club.activities.where(active: true).map { |a| a.ranks}.flatten
		# Filters out everything but the ranks that are active to pass to @first_ranks
		@active_ranks = @ranks.select { |r| r.active == true }
		# Filters out every rank but the first one
		@first_ranks = @active_ranks.select { |ar| ar.position == 1 }
	end

	def create
		@student = current_club.students.build(student_params)
		student_enrolled_on_paid_plan(student_params[:payment_plan_id])
		if @student.save
			if params[:rank_ids].present?
				puts params[:rank_ids][:id].count
				params[:rank_ids][:id].each do |id|
					student_rank = StudentRank.new(:student_id => @student.id,:rank_id => id)
					if student_rank.valid?
						student_rank.save
					end
				end
			end
			flash[:success] = "Student created!"
			redirect_to student_path(@student)
		else
			@payment_plans = current_club.payment_plans.where(active: true)
			@prospect = current_club.payment_plans.first
			@student_ranks = @student.student_ranks.build
			# Gets an array of every rank in the club to pass to @active_ranks
			@ranks = current_club.activities.map { |a| a.ranks}.flatten
			# Filters out everything but the ranks that are active to pass to @first_ranks
			@active_ranks = @ranks.select { |r| r.active == true }
			# Filters out every rank but the first one
			@first_ranks = @active_ranks.select { |ar| ar.position == 1 }
			render 'new'
		end
	end

	def edit
		@student = current_club.students.find_by(id: params[:id])
		@activities = current_club.activities.all
		@ranks = @student.club_ranks
	end

	def update
		@student = current_club.students.find_by(id: params[:id])
		student_enrolled_on_paid_plan(params[:student][:payment_plan_id])
		@ranks = @student.club_ranks
		if @student.update_attributes(student_params)
			flash[:success] = "Student details updated"
			redirect_to @student
		else
			@activities = current_club.activities.all
			render 'edit'
		end
	end

	def destroy
		@student = current_club.students.find_by(id: params[:id])
		if @student.nil?
			redirect_to root_url
		else
			@student.destroy
			flash[:success] = "Student deleted"
			redirect_to students_path
		end
	end
	def attendance
		if params[:search].present?
			@date_find = params[:search].to_date
			@prev_data = Date.parse(params[:search]) - 7.days
			@next_data = Date.parse(params[:search])+ 7.days
		else
			@date_find = params[:date_slot].present? ? Date.parse(params[:date_slot]) : Date.today
			@prev_data = @date_find - 7.days
			@next_data = @date_find + 7.days
		end
		if params[:s_id].present?
			student = Student.find_by(id: params[:s_id])
		end

		if params[:s_id].present? && !params[:remove_attendance].present?
			attendance = current_club.students.find(params[:s_id]).attendances.new
			attendance.attended_on = @date_find
			attendance.activity_id = params[:activity_id]
			attendance.timeslot_id = params[:timeslot_id]
			attendance.attended = true
			attendance.rank_id = attendance.find_rank
			attendance.save

			if student.classes_remaining.present?
				student.classes_remaining = student.classes_remaining - 1
				student.save
			end

		end
		if params[:remove_attendance].present?
			attendance = Attendance.where(timeslot_id: params[:timeslot_id],attended_on: @date_find,student_id: params[:s_id]).first
			attendance.destroy

			if student.classes_remaining.present?
				student.classes_remaining = student.classes_remaining + 1
				student.save
			end
		end

		if student.present?
			@first_name = student.first_name
			@last_name = student.last_name
			@classes_remaining = student.classes_remaining
		end

		activity = Activity.find(params[:activity_id])
		rank_ids = activity.ranks.all.pluck(:id)
		student_for_attendance = current_club.students.where(active: true).student_for_attendance(rank_ids)
		@student_present = student_for_attendance.left_outer_joins(:attendances).where( attendances: { timeslot_id: params[:timeslot_id],attended_on: @date_find } ).reorder(nil).sort_by(&:updated_at).reverse!
		@student_absent = student_for_attendance - @student_present

		respond_to do |format|
		  format.html
		  format.js
		end
	end
	def schedule_classes
		@student = Student.find_by(id: params[:id])
		@activity = @student.all_acitivities.uniq
	end

	def student_attendance
		# @attendance = Attendance.where(student_id: params[:student_id],activity_id: params[:activity_id])
		# @attendance.each do |a|
		# 	puts a.id
		# end
		@activity = Activity.find(params[:activity_id]) if params[:activity_id].present?
		@student = Student.find(params[:student_id]) if params[:student_id].present?
		respond_to do |format|
    	format.html
    	format.json { render json: AttendanceDatatable.new(view_context) }
  	end
	end

	def prospects
		if @club = current_club
			@prospects = TypeOfStudent.active_prospects(current_club)
		else
			flash[:success] = "Student details updated"
			redirect_to root_url
		end
	end

	def absents
    	@students = TypeOfStudent.active_enrolled(current_club)
    	@absent_alert = current_club.absent_alert
     	@absent_alert_activation_date = Date.today - current_club.absent_alert
	end

	#Used for checking whether the student enrolled on paid plan or not
	def student_enrolled_on_paid_plan(plan_id)
		if plan_id.present?
			paid_plan = PaymentPlan.find_by_id(plan_id).name !=  "Prospect"
			if paid_plan
				@student.enrolled_on = Date.today
				create_new_student_metric_record
			else
				@student.enrolled_on = ""
			end
		end
	end

	def create_new_student_metric_record
      DailyMetric.create(
        club_id: @student.club.id,
        new_students: 1
      )
	end

	private

		def exceed_student_limit
			if StudentLimit.over?(current_club)
				flash[:success] = "You've grown to the limit of this plan, well done! Upgrade and keep going!"
				redirect_to subscriptions_path
			end
		end

		def student_params
			params.require(:student).permit(:payment_plan_id, :active, :email, :address_line_1, :address_line_2, :city, :state, :postcode,:enrolled_on,
											:phone1, :phone2, :first_name, :last_name, :dob, :parent1, :parent2,
											:size, :picture, :student_since, :notes, :payment_plan_id, :classes_remaining, :student_rank, rank_ids: [],
											student_ranks_attributes: [:student_id, :rank_id, :active])
		end

		# Before filters

end

app/helpers/students_helper.rb
module StudentsHelper
	class String
	    def capitalize_name
	        name_capitalized = ""
	        self.capitalize!
	        char_array = self.split("")
	        char_array.each_index do |i|
	            if char_array[i-1] == "-" || char_array[i-1] == "'" || char_array[i-1] == " "
	                char_array[i].upcase!
	            end
	            name_capitalized << char_array[i]
	        end
	        name_capitalized.strip.squeeze(" ")
	    end
	end

	#Method for checking student active ranks
	def active_rank(student, rank)
    	return student.ranks.include?(rank)
	end
end

app/views/students/_absent_student.html.erb
<div class="thumbnail scroll-area">
  <div class="absent_div" id="tasks">
    <h3 class="text-center mt-3 mb-3">Absent</h3>
    <% @student_absent.each do |student| %>
      <%= link_to( attendance_students_path(s_id: student.id,date_slot: params[:date_slot],activity_id: params[:activity_id],timeslot_id: params[:timeslot_id]), :remote => true,:class=>"student_attance_div") do %>
        <div class="absent_student d-flex justify-content-start align-content-center mt-2 mb-2">
          <div class="align-self-center m-2">
            <% if student.picture? %>
              <img class="attadance-student-img align-self-center" <%= image_tag student.picture.url %>
            <% else %>
              <img class="attadance-student-img align-self-center" <%= image_tag("no_picture.jpg") %>
            <% end %>
          </div>
              <div class="align-self-center pl-2">
                <span class="student_name"> <%= student.first_name + " " + student.last_name%></span>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

app/views/students/_present_student.html.erb
<div class="thumbnail scroll-area">
  <div class="present_div" >
    <h3 class="text-center mt-3 mb-3">Present: <%= @student_present.count %></h3>
    <% @student_present.each do |student| %>
      <%= link_to( attendance_students_path(s_id: student.id,date_slot: params[:date_slot],activity_id: params[:activity_id],timeslot_id: params[:timeslot_id],remove_attendance: true), :remote => true,:class=>"student_attance_div") do %>
        <div class="present_student d-flex justify-content-start align-content-center mt-2 mb-2">
          <div class="align-self-center m-2">
            <% if student.picture? %>
              <img class="attadance-student-img align-self-center" <%= image_tag student.picture.url %>
         <% else %>
            <img class="attadance-student-img align-self-center" <%= image_tag("no_picture.jpg") %>
         <% end %>
      </div>
              <div class="align-self-center pl-2">
                <span class="student_name"> <%= student.first_name + " " + student.last_name%></span>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

app/views/students/_student.html.erb
<li id="student-<%= student.id %>">
	<span class="details">
		<%= student.first_name %> <%= student.last_name %><br>
		DOB: <%= student.dob %><br>
		Email: <%= student.email %><br>
		Member since <%= time_ago_in_words(student.created_at) %> ago.
	</span>
</li>

app/views/students/index.html.erb
<section class="studentList">
  <% provide(:title, "Students") %>
  <div class="container mt-5">
    <div class="row">
      <div class="offset-2 d-flex justify-content-start  mt-2 mb-2">
        <h4 style="margin-bottom:0px;padding-right: 20px;">
          <span class="bg-success-gradient r-50 custom-shadow"><i class="fa fa-users" title="students"></i></span>
          Students
        </h4>
      </div>
      <%= link_to("Add New Student", new_student_path , :class => "row col-md-6 col-lg-4 col-xl-3 col-12 d-flex flex-column justify-content-center btn new-stu-btn btn-danger") %>
    </div>
    
    <% if @students.none? %>
      <%= link_to("You haven't got students yet! Add your first student here", new_student_path) %><br>
    <% end %>
    <div class="row d-flex justify-content-center align-content-center">
      <% @students.each do |s| %>
        <div class="col-12 ">
          <%= link_to( student_path(s ),:class=>"student-link") do %>
            <div class="student_div d-flex justify-content-start align-content-center mt-2 mb-2">
              <div class="align-self-center  m-2">
                <% if s.picture? %>
                  <img class="student_img align-self-center " <%= image_tag s.picture.url  %>
						<% else %>
							<img class="student_img align-self-center " <%= image_tag("no_picture.jpg") %>
						<% end %>
					</div>
                  <div class="align-self-center pl-2">
                    <p class="student_name"> <%= s.last_name + ", " + s.first_name %></p>
                  </div>
                </div>
                <%# <div class="student  mt-2 mb-2"> %>
                <%# </div> %>
              <% end %>
            </div>
          <% end %>
        </div>
        <%#
		<div class="row">
			<div class="col-12 col-md-6 mt-3 mb-3">
				Average length of membership: <%= @average_membership_length %> <%# days<br>
			</div>
		</div> #%>
        <div class="row d-flex justify-content-center align-content-center mt-4">
          <div class=" text-center">
            <h4><%= link_to '<i class="fa fa-power-off"></i> Show Deactivated Students'.html_safe, deactivated_students_path(@students),:class=>"deactive-student-link" %></h4>
          </div>
        </div>
      </div>
    </section>

app/views/students/show.html.erb
<% provide(:title, @student.first_name) %>
<section class="studentpage">
	<div class="container mt-5">
		<div class="row mt-md-2 mb-md-2 mt-1 mb-1 ">
			<!-- <div class="previous"> -->
			<div class="col-12">
				<p><%= link_to "Student List", students_path , class: "nav_link"  %></p>
				<% if @student.ranks.count == 0 %>
					<i class="text-danger">This student isn't enrolled in any classes. <%= link_to "Enrol here", edit_student_path %></i><br>
				<% end %>
				<% if @student.payment_plan.id == 1 %>
					<i class="text-danger">This student is a prospect. <%= link_to "Upgrade here", edit_student_path %></i>
				<% end %>
				<hr class="staight-line">
			</div>
			<!-- </div> -->
		</div>
		<div class="row mt-4">
			<div class="col-lg-3 col-sm-6 col-12">
				<% if @student.picture? %>
				<img class="single_student_img align-self-center" <%= image_tag @student.picture.url  %>
				<% else %>
				<img class="single_student_img align-self-center" <%= image_tag("no_picture.jpg") %>
				<% end %>
			</div>
			<div class="col-lg-4 col-sm-6 col-12 mt-3 mt-lg-0">
				<p class="single_student_name mt-1"><%= @student.first_name %> <%= @student.last_name %></p>
				<p><% if @student.active == false %>
					<u>INACTIVE</u><br>
					<% end %>
				</p>
				<p><%= @student.email %></p>
				<p><% if @student.size? %>
					Uniform size: <%= @student.size %><br>
					<% end %>
				</p>
				<% if @student.dob? %>
					<p>Date of birth: <%= @student.dob.strftime("%d/%m/%Y") %> (<%= ((Date.today - @student.dob) / 365).to_i %> years old)<br></p>
				<% end %>
				</div>
				<div class="col-lg-3 col-sm-6 col-12 mt-lg-0 mt-sm-3">
					<% if @student.phone1? %>
					<p>Primary phone: <br><br><%= @student.phone1 %></p>
					<p>
						<% if @student.phone2? %>
						Secondary phone: <br><br><%= @student.phone2 %>
						<% end %>
					</p>
					<% end %>
				</div>
				<div class="col-lg-2 col-sm-6 col-12">
					<% if @student.address_line_1? %>
						Address:<br>
						<% if @student.address_line_2? %>
							<%= @student.address_line_2 %> /
						<% end %>
					<% end %>
					<%=@student.address_line_1 %><br>
					<%= @student.city %><br>
					<%= @student.state %><br>
					<%= @student.postcode %><br>
				</div>
			</div>
			<div class="row mt-5  ">
				<div class="col-lg-3 col-sm-6 col-12 pt-4 pt-sm-0">
					<hr class="staight-line">
					<p>Payment plan: <%= @student.payment_plan.name %></p>
					<% unless @student.payment_plan.classes_amount.blank? %>
					<p>Classes remaining: <%= @student.classes_remaining.nil? ? "0" : @student.classes_remaining %></p>
					<%= link_to "Purchase another #{@student.payment_plan.name}", buy_classes_student_path(@student), method: :patch, data: { confirm: "#{@student.first_name} currently has #{pluralize(@student.classes_remaining, 'class')} remaining. Add #{@student.payment_plan.classes_amount} more for $#{@student.payment_plan.price}?" }, class: "btn btn-primary btn-pay"  %><br>
					<% end %>
					<p class="mt-2">Student since: <%= @student_since %> (<%= distance_of_time_in_words_to_now(@time_ago) %>)</p>
					<% if @student.parent1? %>
					<hr class="staight-line">
					<p>Parent/guardian 1: <%= @student.parent1 %></p>
					<% end %>
					<% if @student.parent2? %>
					<p>Parent/guardian 2: <%= @student.parent2 %></p>
					<% end %>
					<% if @student.notes? %>
					<hr class="staight-line">
					<u>Notes:</u> <br>
					<i><%= @student.notes %></i><br>
					<% end %>
				</div>
				<div class="col-lg-4 col-sm-6 col-12">
					<p class="single_student_class">Classes:</p>
					<% if @student.unique_activities.any? %>
					<% @student.student_ranks.where(:active => true).each do |r| %>
					<% if r.rank.activity.active? %>
						<li><%= r.rank.activity.name %> (<%= r.rank.name %>)</li>
					<% end %>
					<% end %>
					<% else %>
					<li>None</li>
					<% end %>
				</div>
				<div class="col-lg-4 col-sm-12 col-12 d-flex  justify-content-between flex-wrap align-items-baseline align-content-start mt-4 mt-lg-0 ">
					<%= link_to "Attendance", student_attendance_students_path(student_id: params[:id]), class: "nav_link custom-link"   %><br>
					<% if @student.active? %>
					<%= link_to "Edit student details", edit_student_path, class: "nav_link custom-link"   %><br>
					<% else %>
					<%= link_to "Reactivate", student_path(@student, :student => { :active => true }),
					:method => :put, data: { :confirm => "Are you sure?" }, class: "btn btn-primary nav_link"  %><br>
					<%= link_to "Delete", @student, method: :delete, data: { confirm: "Please note: only delete students that were entered erroneously. This is permanent and removes all associated student data & statistics. Are you sure you want to delete this student?"}, class: "btn-delete nav_link" %><br>
					<% end %>
				</div>
			</div>
		</div>
	</section>

app/views/students/student_attendance.html.erb
<%= stylesheet_link_tag 'student_attendance', media: 'all' %>

<section class="attendance-sheet">
  <div class="container">
    <div class="row mt-5">
      <div class="col-12">
        <% if params[:student_id].present?  %>
          <h4 style="text-align: center;">
            <span style="font-size: xx-large;"><%= @student.first_name %> <%= @student.last_name %> attendance
            </span>
          </h4>
        <% else %>
          <h4 style="text-align: center;">
            <span style="font-size: xx-large;">
              <%= @activity.name.upcase %> ATTENDANCE SHEET
            </span>
          </h4>
        <% end %>
      </div>
    </div>

    <div class="row" style="margin-bottom: 7px;">
      <div class="col-12">
        <%= form_tag(student_attendance_students_path, :method => "get", id: "search-form",class: "form-inline") do %>
        <div class="col-12" style="left: -45px;">
          <h6><span style=" font-size: larger;font-weight: bold;"><br/>Filter between dates</span></h6>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12 col-sm-6 col-md-4" style="margin-left: -31px;">
        <div class="form-group">
           <div class='input-group date' id='datepicker_from'>
            <label for="email" style="padding-right: 10px;margin-top: 2%;">From:</label> 
            <%= date_field_tag :from_date,params[:from_date],class: "form-control" %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
      </div>
      <span style="padding-right: 20px;">
      </span>
      <div class="col-12 col-sm-6 col-md-4 DateRangeFilter">
        <div class="form-group " >
          <div class='input-group date' id='datepicker_to'>
            <label for="pwd" style="padding-right: 10px;margin-top: 2%;">To:</label> 
            <%= date_field_tag :to_date,params[:to_date],class: "form-control"%>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
        <%= hidden_field_tag :student_id,params[:student_id]%>
        <%= hidden_field_tag :activity_id,params[:activity_id]%>
      </div>
      <div class="col-12 col-sm-6 col-md-4">
        <div class="form-group d-flex align-items-baseline" style="margin-top: -6px !important;">
          <button type="submit" class="btn btn-primary ml-2" >Submit</button>
          <% end %>
          <%= button_to "Reset", student_attendance_students_path(), :class => "btn btn-success m-2", :method => :get, params: { student_id: params[:student_id], activity_id: params[:activity_id] } %>
        </div>
      </div>
    </div>

    <div class="col-12 ">
    </div>

    <div class="table-responsive">
      <table id="products" class="table table-striped table-bordered" cellspacing="0" width="100%" data-source="<%= student_attendance_students_url(student_id: params[:student_id], activity_id: params[:activity_id], format: "json", from_date: params[:from_date], to_date: params[:to_date], club_time_zone: current_club.time_zone) %>">
        <thead>
          <tr>
            <% if params[:student_id].present? %>
              <th>Class Name</th>
            <% elsif params[:activity_id].present? %>
              <th>Student Name</th>
            <% end %>
            <th>Rank</th>
            <th>Time</th>
            <th>Day</th>
            <th>Date</th>
          </tr>
        </thead>
        <tfoot>
        	<tr>
            <% if params[:student_id].present? %>
              <th>Class Name</th>
            <% else %>
              <th>Student Name</th>
            <% end %>
              <th>Rank</th>
              <th>Time</th>
              <th>Day</th>
              <th></th>
          </tr>
        </tfoot>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</section>

<script type="text/javascript">
      $(function () {
        $('#datepicker_from').datetimepicker({
          format: 'DD/MM/YYYY'
        });
        $('#datepicker_to').datetimepicker({
          format: 'DD/MM/YYYY'
        });
        $('#datepicker_search').datetimepicker({
          format: 'DD/MM/YYYY'
        });
      });
</script>