config/routes.rb
Rails.application.routes.draw do

  resources :followers
  resources :blog_images
  get 'charges/new'
  get 'charges/create'
  resources :subscriptions do
    collection do
      get :cancel
      get :change
      get :confirm_plan_change
      get :admin
      get :change_hidden
    end
  end
  root 'static_pages#home'
  get '/signup', to: 'clubs#new'
  post '/signup', to: 'clubs#create'
  get '/metrics', to: 'clubs#metrics'
  get  '/help',    to: 'static_pages#help'
  get '/admin', to: 'static_pages#admin'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/getting_started', to: 'static_pages#getting_started'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :clubs do
    collection do
      get :payment_plans
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :students do
    collection do
      get 'attendance'
      get 'schedule_classes'
      get 'student_attendance'
      get 'prospects'
      get 'deactivated'
      get 'absents'
    end
    patch :buy_classes, on: :member
  end
  resources :activities do
    collection do
      get 'scheduled_classes'
      get 'students'
    end
    member do
      get :grading
            put :update_grading
    end
  end
  resources :payment_plans do
    collection do
      get 'students'
    end
  end
  resources :timeslots
  resources :ranks
  resources :payment_plans
  resource :demo, only: :show, controller: :demo
  resources :charges, only: [:new, :create, :delete]
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  resources :blog_posts do
    collection do
      get 'admin'
    end
  end
end

app/views/shared/_club_info.html.erb
<%# Notifications %>
<% rank_notification_required = false %>
<% current_club.activities.where(active: true).each do |a| %>
  <% unless a.ranks.any? %>
    <% rank_notification_required = true %>
    <% break %>
  <% end %>
<% end %>
<% if current_club.activities.where(active: true).none? %>

<!-- Dwizco youtube pop-up -->
<script async src="https://dwizco.com/socialproof/pixel/v0r6l8llbfvv6zmdmq5o6o58yp9lmope"></script>

  <div class="clubInfoNotifications btn btn-success container p-3 my-3 text-white">
    <%= link_to("Welcome to Attendrr! First, click here to add a class", new_activity_path, class: 'horizontal-line text-white') %>
  </div>
  
<% elsif rank_notification_required %>
  
  <div class="clubInfoNotifications container btn btn-success p-3 my-3 text-white">
    <%= link_to("There are classes without ranks! Click here to add ranks", activities_path, class: 'horizontal-line text-white') %>
  </div>
  
<% elsif current_club.payment_plans.where(active: true).count-1 == 0 %>

  <div class="clubInfoNotifications container btn btn-success p-3 my-3 text-white">
    <%= link_to("Now you need to add at least one payment plan! Click here", new_payment_plan_path, class: 'horizontal-line text-white') %>
  </div>

<% elsif current_club.students.where(active: true).none? %>

  <div class="clubInfoNotifications container btn btn-success p-3 my-3 text-white">
    <%= link_to("It's time to grow your club! Click here to add your first student", new_student_path, class: 'horizontal-line text-white') %>
  </div>

<% elsif (@students.count == 0) && (@prospects.count > 0) %>

  <div class="clubInfoNotifications container btn btn-success p-3 my-3 text-white">
    <%= link_to("You convert Prospects into Students by upgrading their payment plan. Click here!", prospects_students_path, class: 'horizontal-line text-white') %>
  </div>
  
<% end %>
<%# End notification %>
<div class="row mt-md-3 mt-4 ml-2 mr-2">
  <%# <%= link_to scheduled_classes_activities_path , :class => "redirect_div" do %>
    <!-- schedule class -->
    <div class="col-6 col-md-3">
      <%= link_to scheduled_classes_activities_path,class:"homepage-nav" do %>
        <div class="row">
          <div class="div_box col-12 d-flex justify-content-center flex-column">
            <img class="custom_icons align-self-center" src=<%=image_url('calendar.png') %>  alt="" >
            <%# <%= link_to_image("calendar.png", scheduled_classes_activities_path) %>
            <span class="align-self-center text-center redirect_link">Scheduled classes</span>
          </div>
        </div>
      <% end %>
    </div>
    <%# <% end %>
    <!-- Student -->
    <div class="col-6 col-md-3">
      <%= link_to students_path,class:"homepage-nav" do %>
        <div class="row">
          <div class="div_box col-12 d-flex justify-content-center flex-column">
            <img class="custom_icons align-self-center" src=<%=image_url('sport.png') %>  alt="" >
            <%# <%= link_to_image("calendar.png", scheduled_classes_activities_path) %>
            <span class="align-self-center text-center redirect_link">Students</span>
            <span class="align-self-center text-center redirect_link"><%= @students.count %></span>
          </div>
        </div>
      <% end %>
    </div>
    <% absent_students = 0 %>
    <% @students.each do |s| %>
      <!-- <ul> -->
      <% if s.last_attendance < @absent_alert_activation_date %>
        <% absent_students += 1 %>
      <% end %>
      <!-- </ul> -->
    <% end %>
    <!-- absent student -->
    <div class="col-6 col-md-3 mt-2 mt-md-0">
      <%= link_to absents_students_path,class:"homepage-nav" do %>
        <div class="row">
          <div class="div_box col-12 d-flex justify-content-center flex-column">
            <img class="custom_icons align-self-center" src=<%=image_url('absent.png') %>  alt="" >
            <span class="align-self-center text-center redirect_link">Absents</span>
            <span class="align-self-center text-center redirect_link"><%= absent_students %></span>
          </div>
        </div>
      <% end %>
    </div>
    <!-- Prospects  -->
    <div class="col-6 col-md-3 mt-2 mt-md-0">
      <%= link_to prospects_students_path,class:"homepage-nav" do %>
        <div class="row">
          <div class="div_box col-12 d-flex justify-content-center flex-column">
            <img class="custom_icons align-self-center" src=<%=image_url('prospect.png') %>  alt="" >
            <span class="align-self-center text-center redirect_link">Prospects</span>
            <span class="align-self-center text-center redirect_link"><%= @prospects.count %></span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row mt-md-5 mt-2 ml-2 mr-2">
    <%# <%= link_to scheduled_classes_activities_path do %>
      <!-- Class-->
      <div class="col-6 col-md-3">
        <%= link_to activities_path,class:"homepage-nav" do %>
          <div class="row">
            <div class="div_box col-12 d-flex justify-content-center flex-column">
              <img class="custom_icons align-self-center" src=<%=image_url('class.png') %>  alt="" >
              <span class="align-self-center text-center redirect_link">Classes</span>
              <span class="align-self-center text-center redirect_link"> <%= current_club.activities.where(active: true).count %></span>
            </div>
          </div>
        <% end %>
      </div>
      <%# <% end %>
      <!-- Payment -->
      <div class="col-6 col-md-3">
        <%= link_to payment_plans_path,class:"homepage-nav" do %>
          <div class="row">
            <div class="div_box col-12 d-flex justify-content-center flex-column">
              <img class="custom_icons align-self-center" src=<%=image_url('payment.png') %>  alt="" >
              <span class="align-self-center text-center redirect_link">Payment plans</span>
              <span class="align-self-center text-center redirect_link">	<%=  current_club.payment_plans.where(active: true).count-1 %></span>
            </div>
          </div>
        <% end %>
      </div>
      <!-- metrics -->
      <div class="col-6 col-md-3 mt-2 mt-md-0">
        <%= link_to metrics_path,class:"homepage-nav" do %>
          <div class="row">
            <div class="div_box col-12 d-flex justify-content-center flex-column">
              <img class="custom_icons align-self-center" src=<%=image_url('metrics.png') %>  alt="" >
              <span class="align-self-center text-center redirect_link">Metrics</span>
            </div>
          </div>
        <% end %>
      </div>
      <!-- View Club details  -->
      <div class="col-6 col-md-3 mt-2 mt-md-0">
        <%= link_to current_club,class:"homepage-nav" do %>
          <div class="row">
            <div class="div_box col-12  d-flex justify-content-center flex-column">
              <img class="custom_icons align-self-center" src=<%=image_url('eye.png') %>  alt="" >
              <span class="align-self-center text-center redirect_link">View Club Details</span>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row mt-md-5 mt-4 ml-2 mr-2">
      <div class="offset-md-9  col-md-3 col-12">
        <%= link_to new_student_path,class:"homepage-nav" do %>
          <div class="row">
            <div class=" col-12 d-flex justify-content-center add_new_student_div">
              <span class="add_new_student  align-self-end">Add new student</span>
            </div>
          </div>
        <% end %>
      </div>
    </div>

<script type="text/javascript">
  /*Make Entire Club Notifications Clickable*/
  $(".clubInfoNotifications").click(function() {
    window.location = $(this).find("a").attr("href"); 
    return false;
  });
</script>

app/views/shared/_error_messages.html.erb
<section class="error-message-block">
	<div class="container">
		<% if object.errors.any? %>
			<div id="error_explanation">
				<div class="alert alert-danger">
					The form contains <%= pluralize(object.errors.count, "error") %>
				</div>
				<ul>
					<% object.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
	</div>
</section>

app/views/shared/_student_form.html.erb
<%= form_for(@student, html: { multipart: true }) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
	<%= f.label :first_name %>*
	<%= f.text_field :first_name, class: 'form-control' %>

	<%= f.label :last_name %>*
	<%= f.text_field :last_name, class: 'form-control' %>

	<%= f.label :dob, "Date of birth" %>*
	<%= f.date_select :dob, {order: [:day, :month, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year, end_year: Date.today.year - 90}, class: 'form-control' %>

	<%= f.label :email %>*
	<%= f.email_field :email, class: 'form-control' %>

	<%= f.label :address_line_1 %>* Street address, P.O. box, company name, etc.
	<%= f.text_field :address_line_1, class: 'form-control' %>

	<%= f.label :address_line_2 %> Apartment, suite, unit, building, floor, etc.
	<%= f.text_field :address_line_2, class: 'form-control' %>

	<%= f.label :city %>*
	<%= f.text_field :city, class: 'form-control' %>

	<%= f.label :state %>*
	<%= f.text_field :state, class: 'form-control' %>

	<%= f.label :postcode %>*
	<%= f.number_field :postcode, class: 'form-control' %>

	<%= f.label :phone1, "Primary phone" %>*
	<%= f.phone_field :phone1, class: 'form-control' %>

	<%= f.label :phone2, "Secondary phone" %>
	<%= f.phone_field :phone2, class: 'form-control' %>

	<%= f.fields_for :student_rank do |sr| %>
		<%= sr.collection_select(:rank_id, @first_ranks, :id, :activity_name, :include_blank => "Select class") %>
	<% end %>

	<span class="picture">
		<%= f.label :picture, "Attach student picture" %>
		<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
	</span>
	</div>
	<%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

<!-- JQuery. Ensures files size is < 5MB client-side -->
<script type="text/javascript">
  $('#student_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

<% @first_ranks.each do |fr| %>
	<%= fr.name %> | <%= fr.activity.name %> <%= fr.position %><br>
<% end %>