config/routes.rb
Rails.application.routes.draw do

  resources :followers
  resources :blog_images
  get 'charges/new'
  get 'charges/create'
  resources :subscriptions do
    collection do
      get :cancel
      get :change
      get :confirm_plan_change
      get :admin
      get :change_hidden
    end
  end
  root 'static_pages#home'
  get '/signup', to: 'clubs#new'
  post '/signup', to: 'clubs#create'
  get '/metrics', to: 'clubs#metrics'
  get  '/help',    to: 'static_pages#help'
  get '/admin', to: 'static_pages#admin'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/getting_started', to: 'static_pages#getting_started'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :clubs do
    collection do
      get :payment_plans
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :students do
    collection do
      get 'attendance'
      get 'schedule_classes'
      get 'student_attendance'
      get 'prospects'
      get 'deactivated'
      get 'absents'
    end
    patch :buy_classes, on: :member
  end
  resources :activities do
    collection do
      get 'scheduled_classes'
      get 'students'
    end
    member do
      get :grading
            put :update_grading
    end
  end
  resources :payment_plans do
    collection do
      get 'students'
    end
  end
  resources :timeslots
  resources :ranks
  resources :payment_plans
  resource :demo, only: :show, controller: :demo
  resources :charges, only: [:new, :create, :delete]
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  resources :blog_posts do
    collection do
      get 'admin'
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :club
  has_many :timeslots, dependent: :destroy
  accepts_nested_attributes_for :timeslots,:allow_destroy => true
  has_many :ranks, dependent: :destroy
  has_many :attendances, dependent: :destroy
  accepts_nested_attributes_for :ranks
  validates :club_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  has_many :students, through: :ranks
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy, :new, :edit, :update]
	before_action :correct_club, only: [:index, :show, :destroy] # Currently does nothing??
	before_action :exceed_student_limit, only: [:scheduled_classes, :grading]

	def new
		@activity = Activity.new
		@activity.timeslots.build
		@activity.ranks.build
	end

	def students
		@activity = Activity.find(params[:activity])
		@activity_students = @activity.students.where(active: true)
	end

	def create
		@activity = current_club.activities.new(activity_params)
		if @activity.save
			flash[:success] = "New class created!"
			redirect_to activity_path(@activity)
		else
			render 'new'
		end
	end

	def edit
		@activity = current_club.activities.find_by(id: params[:id])
		@active_ranks = @activity.ranks.where(active: true)
		if !@activity.active?
			redirect_to activities_path
		else
			@activity.timeslots.build
		end
	end

	def update
		@activity = current_club.activities.find_by(id: params[:id])
		@active_ranks = @activity.ranks.where(active: true)
		if @activity.update_attributes(activity_params)
			flash[:success] = "Class updated!"
			redirect_to edit_activity_path(@activity)
		else
			render 'edit'
		end
	end

	def show
		@activity = current_club.activities.find_by(id: params[:id])
		# To calculate students for activity_student#index
		@activity_students = @activity.students.includes(:payment_plan).where.not(payment_plans: {name: 'Prospect'}).where(active: true)
		@activity_prospects = @activity.students.includes(:payment_plan).where(payment_plans: {name: 'Prospect'}).where(active: true)
		@active_ranks = @activity.ranks.where(active: true)
		# To calculate average membership length CHANGE THIS
		@students = @activity.students.where(active: true)
		@active_students = @students.uniq
		#Average length of membership
		@accumulated_memberships_in_days = 0
		@students.each do |s|
			if s.active?
				n = (Date.today - s.created_at.to_date).to_i
				@accumulated_memberships_in_days += n
			else
				n = (s.updated_at.to_date - s.created_at.to_date).to_i
				@accumulated_memberships_in_days += n
			end
		end
		if @accumulated_memberships_in_days.nonzero? && @active_students.count.nonzero?
			@average_membership_length = @accumulated_memberships_in_days / @active_students.count
		else
			@average_membership_length = 0
		end

		# Total number of class attendances
		@total_attendances = @activity.attendances.count
		# Total number of sessions held
		@total_sessions = @activity.attendances.count("DISTINCT(attended_on, timeslot_id)")
		# Average attendance
		if @total_attendances.nonzero? && @total_sessions.nonzero?
			@average_attendance = (@total_attendances.to_f / @total_sessions.to_f).round(2)
		else
			@average_attendance = 0
		end

		if @activity.nil?
			redirect_to root_url
		elsif !@activity.active?
			redirect_to activities_path
		end
	end

	def index
		@activities = current_club.activities.all
	end

	def destroy
		@activity = current_club.activities.find_by(id: params[:id])
		if @activity.nil?
			redirect_to root_url
		else
			@activity.destroy
			flash[:success] = "Class deleted"
			redirect_to activities_path
		end
	end

	def grading
		@activity = current_club.activities.find_by(id: params[:id])
		@ranks = @activity.ranks
		@active_ranks = @ranks.where(active: true)
		@students = TypeOfStudent.active_enrolled(current_club)
	end


	def update_grading
		@activity = current_club.activities.find_by(id: params[:id])
		unless params[:grading].nil?
			@ranks = @activity.ranks
			@active_ranks = @ranks.where(active: true)

			@active_ranks.each do |temp|
				unless temp.student_ranks.blank?
					temp.student_ranks.where(student_id: params[:student_ids]).find_each do |stud|
						if params[:grading].include? stud.student_id.to_s
							index = params[:student_ids].index { |x| x == stud.student_id.to_s }
							rank = @active_ranks.find_by_position(params[:rank_positions][index])
							stud.update_attributes(rank_id: rank.id)
						end
					end
				end
			end
			flash[:success] = "Ranks updated"
		  redirect_to grading_activity_path(@activity)
		else
			flash[:warning] = "Must grade at least 1 student"
			redirect_to grading_activity_path(@activity)
		end
	end

	def scheduled_classes
		if params[:search].present?
			@date_find = params[:search].in_time_zone(current_club.time_zone).to_date
			@prev_data = @date_find.prev_day
			@next_data = @date_find.next_day
		else
			@date_find = Time.now.in_time_zone(current_club.time_zone).to_date
			@prev_data = @date_find.prev_day
			@next_data = @date_find.next_day
		end
		day_find = @date_find.strftime('%w').to_i
		# @activity = current_club.activities.joins(:timeslots).where('DATE(timeslots.schedule) = ?', date_find).includes(:timeslots)
		@activity = current_club.activities.joins(:timeslots).where('timeslots.active = ? AND timeslots.day = ? AND activities.active = ? AND DATE(activities.created_at) <= ?', true,day_find,true,@date_find).includes(:timeslots)
	end

	private

		def exceed_student_limit
			if StudentLimit.over?(current_club)
				flash[:success] = "Woah! You have more students than this plan allows! Upgrade to reaccess this function"
				redirect_to subscriptions_path
			end
		end

		def activity_params
			params.require(:activity).permit(:name, :active,
											 :timeslots_attributes => [:id,
																	   :time_start,
																	   :time_end,
																	   :day,
																	   :active,
																	   :schedule,
																	 	 :_destroy],
											 :ranks_attributes => [:id,
											 					   :name,
											 					   :position,
											 					   :active])
		end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/edit.html.erb
<section class="activity-edit-page">
	<div class="container">
		<div class="row mt-5 d-block">
			<h1><%= link_to @activity.name, @activity,class:'link-text-decoration-none', style: "color: black;" %></h1>
			<div class="form-group">
				<div><b>Time slots</b></div>	
				<% @activity.timeslots.where(active: true).each do |t| %>
					<span><%= Date::DAYNAMES[t.day] %> <%= t.time_start.strftime("%I:%M%P") %>-<%= t.time_end.strftime("%I:%M%P") %></span>
					<span><%= link_to "Delete this time slot", timeslot_path(t, timeslot: { active: false }), method: :put, data: { confirm: "Are you sure?" } %></span><br>
				<% end %>
			</div>
			<div class="form-group rounded" style="background-color: #DCDCDC;">
				<%= form_for(@activity) do |f| %>
					<div class="field d-flex editActivityResponsive m-2" style="padding-top: 26px;">
						<%= f.fields_for :timeslots, @activity.timeslots.build do |timeslots_form| %>
							<%= timeslots_form.label :time_start, "Start time" %>
							<%= timeslots_form.time_select :time_start, {ampm: true} %>

							<%= timeslots_form.label :time_end, "End time" %>
							<%= timeslots_form.time_select :time_end, {ampm: true} %>

							<%= timeslots_form.label :day %>
							<%= timeslots_form.select :day, (0..6).map {|d| [Date::DAYNAMES[d], d]} %>
							
							<div style="display: none;"><%= timeslots_form.label :year %>
							<%= timeslots_form.select :year, ((Time.zone.now.year - 30)..(Time.zone.now.year + 10)).to_a.reverse, {:selected => Time.zone.now.year},{ :class => 'form-control' } %></div>
						<% end %>
					</div>
					<div class="m-2"><%= f.submit "Click to add another", class: "btn btn-primary" %></div>
				<% end %>
			</div>
			
			<div class="form-group">
				<div><b>Ranks</b> AKA belts, grades or levels</div>	
				<% @active_ranks.each do |r| %>
					<%= r.position %>. <%= r.name %> <%= link_to "Delete this rank", rank_path(r, rank: {active: false}), method: :put, data: { confirm: "Are you sure?" } %></span><br>
				<% end %>
			</div>

			<div class="form-group rounded" style="background-color: #DCDCDC;">
				<%= form_for(@activity) do |f| %>
					<%= render 'shared/error_messages', object: f.object %>
					<div class="field m-2">
						<%= f.fields_for :ranks, @activity.ranks.build do |ranks_form| %>
							<%= ranks_form.label :name, "Rank" %>
							<%= ranks_form.text_field :name, class: "col-12 col-md-6" %>
						<% end %>
					</div>
					<div class="m-2"><%= f.submit "Click to add another", class: "btn btn-primary" %></div>
				<% end %>
			</div>
			<div class="activityActionBtn">
				<%= link_to "Deactivate this class", activity_path(@activity, :activity => { :active => false }),
												 :method => :put, data: { :confirm => "Are you sure?" }, class: "form-group btn btn-danger " %>
				<!-- DELETE CLASS
				<%= link_to "Delete this class", @activity, method: :delete, data: { confirm: "Please note: only delete classes that were entered erroneously. To remove a class that is no longer active select the 'deactivate' button. Are you sure you want to delete this class?" }, class: "form-group btn btn-danger " %>
				-->
			</div> 
		</div>
	</div>
</section>

app/views/activities/grading.html.erb
<section class="activitiy-grading-page">
	<div class="container">
		<div class="row mt-5">

		</div>

		<% provide(:title, "Grading") %>
		<% if @students.present? %>
			<div class="grade-head">
				<h4>
					<%= @activity.name %>
					<span>Grading?</span>
				</h4>

			</div>
			<div class="select-gradings">
				<button type="button" class="btn btn-primary checkAll">Select all</button>
			</div>
			<%= form_for(@activity, url: update_grading_activity_path, method: 'put') do |f| %>
				<%= render 'shared/error_messages', object: f.object %>
				<div class="field grading-section-margin">
					<%-# NAROLA - please tidy this and move it out of the view -%>
					<ul class="grade-list-bx">
						<% @students.each do |s| %>
							<% s.student_ranks.each do |sr| %>
								<% if sr.rank.activity == @activity && sr.active? %>
									<li class="grading-section">
										<% if s.picture? %>
											<img class="student_img align-self-center" <%= image_tag s.picture.url  %>
										<% else %>
											<img class="student_img align-self-center" <%= image_tag("no_picture.jpg") %>
										<% end %>
										<span class="first">
											<%= link_to s.first_name + " " + s.last_name, student_path(s) %> <%= sr.rank.name %>
										</span>
										<span class="middle DrodownMargin">
											<%= hidden_field_tag "student_ids[]", s.id %>
											<%= select_tag "rank_positions[]", options_from_collection_for_select(@active_ranks, :position, :name, @active_ranks.maximum(:position) == sr.rank.position ? { selected: sr.rank.position } : { selected: sr.rank.position + 1 }) %>
										</span>
										<label class="customcheck">
											<%= check_box_tag 'grading[]', s.id, false %>
										  <span class="checkmark"></span>
										</label>

									</li>
								<% end %>
							<% end %>
						<% end %>
					</ul>
				</div>
				<%= f.submit "Update ranks", class: "btn btn-primary" %>
			<% end %>
		<% else %>
			<h4>No students</h4>
		<% end %>
	</div>

</section>


<script type="text/javascript">
     
	(function($) {
	    $.fn.clickToggle = function(func1, func2) {
	        var funcs = [func1, func2];
	        this.data('toggleclicked', 0);
	        this.click(function() {
	            var data = $(this).data();
	            var tc = data.toggleclicked;
	            $.proxy(funcs[tc], this)();
	            data.toggleclicked = (tc + 1) % 2;
	        });
	        return this;
	    };
	}(jQuery)); 

	$(".checkAll").clickToggle(function() {
		$("input:checkbox").prop('checked', true);
	}, function() {
		$("input:checkbox").prop('checked', false);
	});
	
</script>

app/views/activities/index.html.erb
<section class="acivities-list">
	<div class="container">
		<div class="row mt-5">
			<div class="col-12 col-md-4">
				<h1 class="text-md-left text-center">Class List</h1>
			</div>
			
		</div>
			
			<% @activities.where(active: true).each do |a| %>
				<div class="row mt-4">
					<div class="col-12 col-md-6  p-3 class-box  mt-1">
						<span><%= link_to a.name, activity_path(a),class:'class-name' %></span>
						<% unless a.ranks.where(active: true).any? %> <%= link_to "This class has no ranks! Add ranks here", edit_activity_path(a) ,class:'add-rank-link'%> <% end %>
					</div>
				</div>
			<% end %>

			<div class="addNewClassBtn">
				<span class="add_new_student align-self-center"><%= link_to("Add new class", new_activity_path) %></span>
			</div>
	</div>
</section>

app/views/activities/new.html.erb
<section class="activity-edit-page">
	<div class="container">
		<div class="row mt-5 d-block">
			<h1>Create New Class</h1>
			<%=  nested_form_for(@activity) do |f| %>
				<%= render 'shared/error_messages', object: f.object %>
					<div class="form-group rounded p-2" style="background-color: #DCDCDC;">	
						<div class="field m-2">
							<b><%= f.label :name, "Class" %></b> (e.g. karate, kung fu, kickboxing, etc..)
							<%= f.text_field :name %>
						</div>
					</div>

					<div class="form-group rounded p-2" style="background-color: #DCDCDC;">
						<!-- RANKS -->
						<div>What <b>Ranks</b> (AKA belts, grades or levels) can students achieve in this class:</div>
						<div class="field m-2 rankTextBoxWidth">
							<%= f.fields_for :ranks, @activity.ranks.build do |ranks_form| %>
								<%= ranks_form.label :name, "Add a rank:" %>
								<%= ranks_form.text_field :name %>

								<%= ranks_form.link_to_remove "Remove this rank" , class: "btn btn-danger form-group" %>
							<% end %>
							<%= f.link_to_add "Click to add another", :ranks , class: "btn btn-success form-group" %>
						<!-- RANKS END -->
						</div>
					</div>

					<div class="form-group rounded p-2" style="background-color: #DCDCDC;">
						<div><b>Time slots</b> (what times and days of the week does this class occur):</div>
						<div class="field m-2 activitiesNewSlotsPanel" style="padding-top: 15px;">
							<%= f.fields_for :timeslots do |timeslots_form| %>
								<%= timeslots_form.label :time_start, "Start time" %>
								<%= timeslots_form.time_select :time_start, {ampm: true} %>

								<%= timeslots_form.label :time_end, "End time" %>
								<%= timeslots_form.time_select :time_end, {ampm: true} %>

								<%= timeslots_form.label :day %>
								<%= timeslots_form.select :day, (0..6).map {|d| [Date::DAYNAMES[d], d]} %>

								<%= timeslots_form.link_to_remove "Remove this timeslot" , class: "btn btn-danger form-group" %>
							<% end %>
							<%= f.link_to_add "Click to add another", :timeslots , class: "btn btn-success form-group"  %>
						</div>
					</div>

				<%= f.submit "Create class", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</section>
<script type="text/javascript">
	$(function () {
                $('.datetimepicker3').datetimepicker({
        			format: 'HH:mm'
                });
                $('.datetimepicker4').datetimepicker({
                	format: 'DD/MM/YYYY'
                });
               $("#new_activity").on("click", ".datetimepicker3", function(event){
               	$(this).datetimepicker({
        			format: 'HH:mm'
                }).datetimepicker( "show" );
				});
               $("#new_activity").on("click", ".datetimepicker4", function(event){
               	$(this).datetimepicker({
               		format: 'DD/MM/YYYY'
               	}).datetimepicker( "show" );
				});
            });
</script>

app/views/activities/scheduled_classes.html.erb
<section class="scheduled_class mt-3">
  <div class="container text-center bg-grey">
    <div class="row">
      <div class="col-12 justify-content-center align-item-center mb-1">
        <h4><%= @date_find.strftime("%A, #{@date_find.day.ordinalize} %B %Y")%></h4>
      </div>
      <!-- <div class="row justify-content-center"> -->
      <div class="col-12 offset-md-3 col-md-6 co justify-content-center align-item-center">
        <%= form_tag(scheduled_classes_activities_path, :method => "get", id: "search-form",class: "center-block") do %>
          <div class="input-group">
            <%= date_field_tag :search, params[:search], class: 'form-control', placeholder:  (Time.zone.now.in_time_zone(current_club.time_zone)).strftime('%d/%m/%y'),id: 'datetimepicker4',required: true %>
            <span class="input-group-btn go_button">
              <%= content_tag :button ,:type => :submit, :class => 'btn btn-default ' do %>
                Go!
              <% end %>
            </span>
          </div>
          <!-- /input-group -->
        <% end %>
      </div>
      <!-- /.col-lg-6 -->
      <!-- </div> -->
    </div>
    <div class="row mt-md-5 mb-md-5 mt-3 mb-3 d-flex justify-content-between">
      <div class=" previous"><%= link_to(@prev_data.strftime(" Previous Day  "), scheduled_classes_activities_path(search: @prev_data)) %></div>
      <div class=" next "><%= link_to(@next_data.strftime(" Next Day "), scheduled_classes_activities_path(search: @next_data)) %></div>
    </div>
    <% if @activity.present? %>
      <div class="row text-center">
        <% @activity.each do |activity| %>
          <% activity.timeslots.each do |timeslot| %>
            <div class="col-12 col-md-4 scheduled_class_div">
              <%= link_to attendance_students_path(date_slot: @date_find,activity_id: activity.id,timeslot_id: timeslot.id) do %>
                <div class=" row thumbnail hoverDiv attendance_class-remove-test attendance-box  mt-2 mb-2 p-md-2 p-1">
                  <div class="col-12">
                    <p class="schedule_time"><%= timeslot.time_start.strftime("%I:%M%P")%> - <%= timeslot.time_end.strftime("%I:%M%P")%></p>
                  </div>
                  <div class="col-12 align-self-center" >
                    <p class="schedule_name" ><strong><%= activity.name %></strong></p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <p>There is no class on this date</p>
    <% end %>
  </div>
</section>
<script type="text/javascript">
  $(function () {
  	$('#datetimepicker4').datetimepicker({
  		format: 'DD/MM/YYYY'
  	});
  });
</script>

app/views/activities/show.html.erb
<section class="single-activies">
	<div class="container">
		<div class="row mt-5 mb-4">
			<div class="col-12 col-md-4">
				<h4 class="text-center text-md-left"><%= @activity.name %></h4>
			</div>
			<div class="col-12 col-md-8 d-flex justify-content-md-end justify-content-start align-self-start flex-wrap">
				<div class="p-2 m-1">
					<%= link_to "Grading", grading_activity_path(@activity),class:"nav_link custom-link" %>
				</div>
				<div class="p-2 m-1">
					<%= link_to "Attendance", student_attendance_students_path(activity_id: params[:id]),class:"nav_link custom-link"  %>
				</div>
				<div class="p-2 m-1">
					<%= link_to "Edit class details", edit_activity_path(@activity),class:"nav_link custom-link"  %>
				</div>
			</div>
		</div>
		<div class="row front-dashboard">
			<div class="col-md-4 col-sm-6">
				<div class="white-box">
					<div class="row  justify-content-between">
						<div class="col-xs-3">
							<div>
								<span class="bg-success-gradient"><%= icon('fas', 'users') %></span>
							</div>
						</div>
						<div class="col-xs-9 text-right">
							<span class="widget-title"> Total Students</span><br>
							<span class="counter"><%= link_to @activity_students.count.to_s + " enrolled | " + @activity_prospects.count.to_s + " prospects", students_activities_path(activity: @activity.id) %></span>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="white-box">
					<div class="row justify-content-between ">
						<div class="col-xs-3">
							<div>
								<span class="bg-success-gradient"><%= icon('fas', 'users') %></span>
							</div>
						</div>
						<div class="col-xs-9 text-right">
							<span class="widget-title"> Avg.  membership</span><br>
							<span class="counter"><%= pluralize(@average_membership_length, 'day') %></span>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4 col-sm-6">
				<div class="white-box">
					<div class="row justify-content-between">
						<div class="col-xs-3">
							<div>
								<span class="bg-warning-gradient"><%= icon('fas', 'percentage') %></span>
							</div>
						</div>
						<div class="col-xs-9 text-right">
							<span class="widget-title"> Avg. attendance </span><br>
							<span class="counter"><%= @average_attendance %></span>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row mt-2">
			<div class="col-12 col-md-6 pl-0">
				<% unless @active_ranks.any? %>
				<div class="col-12 pl-0">
					<h5><%= link_to "All classes need at least one rank. Click here to add ranks.", edit_activity_path(@activity),class:'add-rank-link' %></h5>
				</div>
				<% end %>
				<% if @activity.timeslots.where(active: true).any? %>
				<div class="col-12 pl-0">
					<h4>Class times:</h4>
				</div>
				<div class=" col-12 ">
					<% @activity.timeslots.where(active: true).each do |t| %>
					<div class=" col-12 d-flex  "><p><%= Date::DAYNAMES[t.day] %> <%= t.time_start.strftime("%I:%M%P") %> - <%= t.time_end.strftime("%I:%M%P") %></p></div>
					<% end %>
				</div>
				<% else %>
				<%= link_to "This class has no timeslots! Click here to assign timeslots", edit_activity_path(@activity) %><br>
				<% end %>
			</div>
			<div class="col-12 col-md-6 pl-0 mt-md-0 mt-2">
				<% if @active_ranks.any? %>
				<div class="col-12 pl-0">
					<h4>Ranks:</h4>
				</div>
				<div class=" col-12 ">
					<% @active_ranks.each do |r| %>
					<div class=" col-12 d-flex  "><p><%= r.position %>. <%= r.name %></p></div>
					<% end %>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</section>

app/views/activities/students.html.erb
<section class="studentList">
	<% provide(:title, @activity.name) %>
	<div class="container mt-5">
		<div class="row">
			<div class="col-12 d-flex justify-content-start  mt-2 mb-2">
				<h1 style="margin-bottom:0px;"><%= @activity.name %></h1>
			</div>
		</div>
		<% if @activity_students.none? %>
			<%= link_to("You haven't got students in this class yet! Add students here", new_student_path) %><br>
		<% end %>
		<% @activity_students.each do |s| %>
		<div class="row">
			<div class="col-md-6 col-12 ">
				<%= link_to( student_path(s ),:class=>"student_div") do %>
				<div class="student d-flex justify-content-start align-content-center mt-2 mb-2">
					<div class="align-self-center m-2">
						<% if s.picture? %>
							<img class="student_img align-self-center" <%= image_tag s.picture.url  %>
						<% else %>
							<img class="student_img align-self-center" <%= image_tag("no_picture.jpg") %>
						<% end %>
					</div>
					<div class="align-self-center pl-2">
						<span class="student_name"> <%= s.last_name + ", " + s.first_name %></span>
					</div>
				</div>
				<% end %>
			</div>
		</div>
		<% end %>

</section>